# Goal : liste de coordonnées (x, y) + liste de booléens pour les photos
float64[] waypoints_x
float64[] waypoints_y
bool[]    take_photo

---
# Result
bool   success
string message

---
# Feedback
int32   current_waypoint_index
int32   waypoints_remaining
float32 distance_remaining
float64 estimated_time_remaining
float64 robot_x
float64 robot_y
bool    is_taking_photo
